<a href="https://colab.research.google.com/github/Maione-Anika-Reyes/58010-DSAA/blob/main/Laboratory_10(unfinished).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import numpy as np

X = np.array([[1,1,1],
              [3,-2,-1],
              [-1,4,2]], dtype=float)

Y = np.array([[1],
              [4],
              [-3]],dtype=float)

print(X)
print("\n",X.shape)
print("\n",Y)
print("\n",Y.shape)

[[ 1.  1.  1.]
 [ 3. -2. -1.]
 [-1.  4.  2.]]

 (3, 3)

 [[ 1.]
 [ 4.]
 [-3.]]

 (3, 1)
