<a href="https://colab.research.google.com/github/Maione-Anika-Reyes/58010-DSAA/blob/main/Laboratory_9(unfinished).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

A = np.array([[1,4],
              [0,3]])

np.linalg.det(A)

## Now other mathematics classes would require you to solve this by hand,
## and that is great for practicing your memorization and coordination skills
## but in this class we aim for simplicity and speed so we'll use programming
## but it's completely fine if you want to try to solve this one by hand.
B = np.array([[1,3,5,6],
              [0,3,1,3],
              [3,1,8,2],
              [5,2,6,8]])
np.linalg.det(B)


-235.0000000000002

Coding Activity 9


In [6]:
#Associative Property

import numpy as np

a = np.array([[0,3,1],
              [6,1,2],
              [5,7,9]])

b = np.array([[1,2,1],
              [7,2,0],
              [2,3,6]])

c = np.array([[1,5,0],
              [3,6,9],
              [2,4,6]])

Assoc1 = np.dot(np.dot(a,b),c)
Assoc2 = np.dot(a, np.dot(b,c))
print("Associative Property: \n")
print("Result 1:\n",Assoc1)
print("Result 2:\n",Assoc2)

Associative Property: 

Result 1:
 [[ 62 193 117]
 [113 277 288]
 [343 902 813]]
Result 2:
 [[ 62 193 117]
 [113 277 288]
 [343 902 813]]


In [7]:
#Distributive Property

import numpy as np

a = np.array([[0,3,1],
              [6,1,2],
              [5,7,9]])

b = np.array([[1,2,1],
              [7,2,0],
              [2,3,6]])

c = np.array([[1,5,0],
              [3,6,9],
              [2,4,6]])

dstrb1 = np.dot(a,b,+c)
dstrb2 = np.dot(a,b) + np.dot(a,c)

print("Distributive Property\n")
print("Result 1: \n",dstrb1)
print("Result 2: \n",dstrb2)


Distributive Property

Result 1: 
 [[23  9  6]
 [17 20 18]
 [72 51 59]]
Result 2: 
 [[ 34  31  39]
 [ 30  64  39]
 [116 154 176]]


In [ ]:
#Scalar

import numpy as np

a = np.array([[0,3,1],
              [6,1,2],
              [5,7,9]])

b = np.array([[1,2,1],
              [7,2,0],
              [2,3,6]])

c = 6

